server:
  port: 8901

spring:
  profiles:
    #引入redis配置
    include: redis
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.5.58:3306/181_realestate?serverTimezone=GMT%2B8
    username: root
    password: root
    #druid数据库连接池配置
    druid:
      #初始化连接池数量
      initialSize: 5
      #最大连接池数量
      maxActive: 10
      #最小连接池数量
      minIdle: 5
      #连接池最大等待时间
      maxWait: 30000
      #最小执行连接池空闲销毁时间
      minEvictableIdleTimeMillis: 30000
      #最大执行连接池空闲销毁时间
      maxEvictableIdleTimeMillis: 35000
      #引用拦截器
      #filters: wall,log4j

mybatis:
  mapper-locations: classpath:com/yibayi/dao/**/*.xml,classpath:com/yibayi/core/temp/shiro/dao/*.xml

#logging:
#  config: classpath:./logback-boot.xml
#  path: d:/logs/yibayi
#  pattern:
#    console: %d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n
#    file: %d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n

token:
  cookieName: AUTH_TOKEN
  #181服务域名列表 - 涉及登陆用户的服务域名必填
  #serverDomains:localhost,181.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl